services:
  wordpress:
    image: wordpress:latest
    ports:
    - "8080:80"
    depends_on:
    - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
    - ./themes/mytheme:/var/www/html/wp-content/themes/mytheme
    - ./uploads:/var/www/html/wp-content/uploads
  db:
    image: mariadb:10 
    env_file: .env
    ports:
    - 13306:3306
    volumes:
    - mysql_db_path:/var/lib/mysql
volumes:
  mysql_db_path: