version: "3"
services:
  wordpress:
    image: wordpress:latest
    ports:
    - "8080:80"
    depends_on:
    - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
    - ./themes/mytheme:/var/www/html/wp-content/themes/mytheme
  db:
#    image: mysql:5.7
    build: ./db-data
    env_file: .env
    expose:
    - 3306
    volumes:
#    - ./my.cnf:/etc/mysql/my.cnf
    - ./db-data/datastore:/var/lib/mysql
