version: "2"
services:
  wordpress:
    image: wordpress:latest
    ports:
    - "8080:80"
    depends_on:
    - db
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
    - mytheme:/var/www/html/wp-content/themes/mytheme
  db:
    image: mysql:5.7
    env_file: .env
    expose:
    - 3306
    volumes:
    - db-data:/var/lib/mysql
volumes:
    db-data:
         driver: local
    mytheme:
         driver: local